services:
  chemtools_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "uvicorn app:app --host $APP_HOST --port $APP_PORT --reload"]
    environment:
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      MINIO_HOST: minio
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio
    env_file: .env

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    env_file:
      - .env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    env_file:
      - .env

volumes:
  postgres_data:
  minio_data:
