version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[%(asctime)s] %(levelname)8s | %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO

  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: ../logs/chemtools_manager_logger.log
    mode: a

root:
  level: DEBUG
  handlers: [console, file]
