"""init

Revision ID: 8899a8ff91d4
Revises:
Create Date: 2025-03-01 15:44:56.823514

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8899a8ff91d4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("queue_priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "calculations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.Enum("chargefw2", "mole2", "gesamt", name="dockerizedtoolenum"), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "running", "success", "failure", name="calculationstatusenum"), nullable=False
        ),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("user_ip", sa.String(), nullable=True),
        sa.Column("time_started", sa.DateTime(), nullable=True),
        sa.Column("time_finished", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calculations")
    op.drop_table("users")
    # ### end Alembic commands ###
