services:
  chemtools_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8010
    volumes:
      - .:/app
    ports:
      - 8010:8010
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chemtools_db
    expose:
      - 5432

volumes:
  postgres_data:
