"""user-file-null-user

Revision ID: f78a19a39edc
Revises: 7ee0eb4a2bf7
Create Date: 2025-03-16 23:33:10.221004

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f78a19a39edc"
down_revision: Union[str, None] = "7ee0eb4a2bf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_files", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_files", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
