"""init

Revision ID: 7ee0eb4a2bf7
Revises:
Create Date: 2025-03-16 22:39:16.237455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ee0eb4a2bf7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("output_files", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fetched_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_name_hash", sa.String(), nullable=False),
        sa.Column("molecule_id", sa.String(), nullable=False),
        sa.Column("site", sa.Enum("alphafold", "rcsb_pdb", "pubchem", name="moleculerepositeenum"), nullable=False),
        sa.Column("extension", sa.Enum("cif", "pdb", "sdf", name="moleculefileextensionenum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("user_host", sa.String(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_name_hash", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calculation_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.Enum("chargefw2", "mole2", "gesamt", name="dockerizedtoolenum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "success", "cached", "failure", name="calculationstatusenum"),
            nullable=False,
        ),
        sa.Column("input_files", sa.JSON(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("calculation_result_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("user_host", sa.String(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_result_id"],
            ["calculation_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calculation_requests")
    op.drop_table("user_files")
    op.drop_table("pipelines")
    op.drop_table("fetched_files")
    op.drop_table("calculation_results")
    # ### end Alembic commands ###
