"""update-pipelines

Revision ID: f35be75e408b
Revises: bc386e18d674
Create Date: 2025-03-30 10:42:49.899878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35be75e408b'
down_revision: Union[str, None] = 'bc386e18d674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_requests', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.drop_column('pipelines', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('calculation_requests', 'sequence_number')
    # ### end Alembic commands ###
